name: build docker
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-npm-install:
    strategy:
      matrix:
        version: [20, lts/*]
        os: [ubuntu-latest, ubuntu-22.04]
        include:
          - os: ubuntu-latest
            version: 18
    runs-on: ${{ matrix.os }}
    steps:
        - name: checkout
          uses: actions/checkout@v6
        - name : setup node
          uses: actions/setup-node@v6
          with:
            node-version: ${{ matrix.version }}
        - uses: actions/cache@v5
          with:
            path: ./node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-
        - name: run install
          shell: bash
          run: |
            npm install

  run-npm-test:
    needs: run-npm-install
    strategy:
      matrix:
        version: [20, lts/*]
        os: [ubuntu-latest, ubuntu-22.04]
        include:
          - os: ubuntu-latest
            version: 18

    runs-on: ${{ matrix.os }}
    steps:
        - name: checkout
          uses: actions/checkout@v6
        - name : setup node
          uses: actions/setup-node@v6
          with:
            node-version: ${{ matrix.version }}
        - uses: actions/cache@v5
          with:
            path: ./node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-
        - name: run test
          shell: bash
          run: |
            npm test

  docker-build:
    needs: run-npm-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'main'
    steps:
        - name: checkout
          uses: actions/checkout@v6
        - run: |
            docker build -t ${{ github.sha }} .
