name: npm test
on: 
  workflow_dispatch:

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: TODO
          run: echo "TODO"

        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: 'lts/*'

        - name: run test
          shell: bash
          run: |
            npm install
            npm test