name: npm test
on: 
  workflow_dispatch:

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name : test app
          uses: myRepo/ReusableWorkflow/.github/workflows/test-npm.yaml@main